spring:
  ## spring 서버 local로 돌릴때
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/entertainment?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  ##
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
app:
  firebase-configuration-file: ./serviceAccountKey.json
  firebase-bucket: silvertime-16cf3.appspot.com
